spring:
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/tt?characterEncoding=utf-8
    username: root
    password: root

#  thymeleaf:
#    prefix: classpath:/templates/
#    check-template-location: true
#    cache: false
#    suffix: .html
#    encoding: UTF-8
#    mode: HTML5

##pagehelper分页插件
#pagehelper:
#  #数据库的方言
#  helperDialect: mysql
#  #启用合理化，如果pageNum < 1会查询第一页，如果pageNum > pages会查询最后一页
#  reasonable: true
